 
<!-- Correct script tags for JS files -->
<script src="<?= base_url('public/assets/js/auth-register.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/bootstrap-modal.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/bundle.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-chat-box.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-multiple-upload.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-statistic.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-table.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/components-user.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/custom.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/features-post-create.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/features-posts.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/features-setting-detail.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/forms-advanced-forms.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-advanced-route.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-draggable-marker.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-geocoding.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-geolocation.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-marker.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-multiple-marker.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-route.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/gmaps-simple.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/index.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-calendar.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-chartjs.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-datatables.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-ion-icons.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-slider.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/slider.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-sparkline.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-sweetalert.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-toastr.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/modules-vector-map.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/scripts.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/stisla.js'); ?>"></script>
  <script src="<?= base_url('public/assets/js/utilities-contact.js'); ?>"></script>


  <script src="<?= base_url('public/frontend/js/bootstrap.min.js'); ?>"></script>
  <script src="<?= base_url('public/frontend/js/jquery.colorbox.js'); ?>"></script>
  <script src="<?= base_url('public/frontend/js/map.js'); ?>"></script>
  <script src="<?= base_url('public/frontend/js/script.js'); ?>"></script>
  <script src="<?= base_url('public/frontend/js/shuffle.min.js'); ?>"></script>
  <script src="<?= base_url('public/frontend/js/slick.min.js'); ?>"></script>

  <script src="<?= base_url('public\admin_panel\dist\assets\js\hope-ui.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\apexcharts.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\dashboard.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\vectore-chart.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\widgetcharts.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\external.min.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\libs.min.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\calender.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\circle-progress.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\countdown.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\flatpickr.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\form-wizard.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\fslightbox.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\kanban.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\prism.mini.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\setting.js'); ?>"></script>
  <script src="<?= base_url('public\admin_panel\dist\assets\js\slider-tabs.js'); ?>"></script>
